tortycolis:
    users:
        - id: fd00e6b4-6773-11ee-b429-00155d5de71c
          email: r.nzaou@sncf.fr
          password: $2y$10$YcfFWF3jcQvmpHbVjU.EL.LB42eezTeGOjw5PSP74DXVF.7Bi9Er6 # Coucou12345
          role: ADMINISTRATOR
        - id: a2946d6c-6774-11ee-9beb-00155d5de71c
          email: jean-laurent@sncf.fr
          password: $2y$10$YcfFWF3jcQvmpHbVjU.EL.LB42eezTeGOjw5PSP74DXVF.7Bi9Er6
          role: DELIVERY_PERSON
        - id: f075d358-726f-11ee-a04f-00155dcb0f37
          email: safae-lachgar@sncf.fr
          password: $2y$10$YcfFWF3jcQvmpHbVjU.EL.LB42eezTeGOjw5PSP74DXVF.7Bi9Er6
          role: DELIVERY_PERSON
spring:
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    datasource:
        url: jdbc:postgresql://localhost:5432/tortycolis
        username: postgres
        password: mysecretpassword