tortycolis:
    foo: 1
    users:
        - id: fd00e6b4-6773-11ee-b429-00155d5de71c
          email: r.nzaou@sncf.fr
          password: $2y$10$PSiQ5pH3QpZjQWqf3eRZIexRNhhedNMXMWG8BDtZpZh.xHFSti7QO
          role: ADMIN
        - id: a2946d6c-6774-11ee-9beb-00155d5de71c
          email: jean-laurent@sncf.fr
          password: $2y$10$1o81cb8wMl38U/oDbjAV.OqNgY0oEwCH6fSaJUaEY5yd0H4R2cy4q
          role: DELIVERY_PERSON
spring:
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    datasource:
        url: jdbc:postgresql://localhost:5432/tortycolis
        username: postgres
        password: mysecretpassword